services:
  api:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_mmaturity
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maturity_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
